### PR TITLE
Draft of Akrida changes for IAS Controller Issuance load tests

### PR DESCRIPTION
**Pull request by loneil**
Committing the load testing changes and instructions needed (so far) for testing the IAS Issuance controller here.

See changes needed and steps to run the tests in the README that is part of this PR
https://github.com/bcgov/aries-load-generator/pull/7/files?short_path=e690224#diff-e690224281f8067dc4441e9d72ea9cbb922a759d468f3a68dc3ba0813ea8eca3

### CODE REVIEW

**Comment by loneil** [comment]
@swcurran / @esune Requesting review just for visibility but I don't think we'd merge this to this repo or anything...
Probably alter later to **just** be instructions and maybe a couple supporting files but other stuff into the Akrida framework with some parametrization later on.

**Comment by swcurran** [comment]
Some notes on my try to do this:

- When pushing this back to Akrida, I suspect we can just drop the "IAS_" from the environment variable names so they can be applied to any scenario where we are hitting an Aries Controller from any framework.
- The INVITATION_URL might be the "CONNECTIONS_URL" to parallel the "OOB_URL" above it in the docker file -- same purpose, just uses a different protocol.
- Nice to have is the curl command to call for initializing and deleting a test in the docs, eg:
  - `curl -v --header "X-API-KEY: <API-KEY>" --request POST https://idsit.gov.bc.ca/vc-test/load-tests?workers=100`
  - `curl -v --header "X-API-KEY: <API-KEY>" --request DELETE https://idsit.gov.bc.ca/vc-test/load-tests/<alias>`
- If you have been running Akrida previously, need to run `docker compose -f docker-compose.yml build` before running. Perhaps with the `--no-cache` option.
- I think I did all the setup steps (and the feedback was good), but in the logs I got this error in receiving the credentials:

```
AnonCredsError: Unable to retrieve credential definition with id 7xjfawcnyTUcduWVysLww5:3:CL:28075:PersonSIT: notFound unable to resolve credential definition: Did '7xjfawcnyTUcduWVysLww5' not found on any of the ledgers (total 1).
load-agent-1  |     at LegacyIndyCredentialFormatService.acceptOffer (/load-agent/load-agent/node_modules/@aries-framework/anoncreds/src/formats/LegacyIndyCredentialFormatService.ts:247:13)
load-agent-1  |     at async V1CredentialProtocol.acceptOffer (/load-agent/load-agent/node_modules/@aries-framework/anoncreds/src/protocols/credentials/v1/V1CredentialProtocol.ts:604:28)
load-agent-1  |     at async CredentialsApi.acceptOffer (/load-agent/load-agent/node_modules/@aries-framework/core/src/modules/credentials/CredentialsApi.ts:305:25)
load-agent-1  |     at async EventEmitter.onCredential (/load-agent/load-agent/agent.ts:363:9) {
load-agent-1  |   [cause]: undefined
load-agent-1  | }
```

**Comment by loneil** [comment]
Updated to improve
- No longer saying to update BaseAgent in AFJ (that was a red herring) for Ledger.
- Instructions for env file ledger setting. IDIM SIT needs Candy (error from Stephen's comment above)
- Fixed an exception being thrown
- Added a wait to not get 404s (at least in the few tests I've been doing, not sure if arbitrary wait is appropriate)

Can get issue/receive run throughs without any failures now. Only tried limited small tests though at this point

image

**Comment by loneil** [comment]
Removed code and documentation that has since been merged into Akrida core codebase

**Comment by loneil** [comment]
Reorged docs https://github.com/bcgov/akrida-bc-load-generator-scripts/pull/11

**Pull request closed without merging**
