### PR TITLE
Verifier akrida setup

### PR DESCRIPTION
**Pull request by loneil**
WIP, adding test files (and any Akrida changes needed) as we go here...

https://github.com/bcgov/aries-load-generator/issues/8

Note: 
Should merge in https://github.com/hyperledger/aries-akrida/pull/45 if that is sorted so we don't need those changes here. If not will need those fixes applied to local.

### CODE REVIEW

**Comment by swcurran** [comment]
Ran a test today and got some good results (fast -- with one test agent, I was getting ~287 verifies/min), but some not so good things. Two issues:

1. The "on_start" task count kept rising after the full slate of agents were started. I would have expected it to stop rising once it hit the size of the swarm.  For example, with a swarm size of 40, I had 234 "on_start" executions. @loneil -- is that expected?
2. After about 2 minutes, I started to get errors.  The first error seems to be losing access to the ledger.   Saw the same behaviour twice, once when I had three swarms running, and all started to get errors at the same time, a second time with a single swarm that had been running about 2.5 minutes.

```
oad-agent-1  | AriesFrameworkError: Credential definition not found for id DGxFt25rfxSecGiHDt79J3:3:CL:249336:rev2: unable to resolve credential definition: IndyError(PoolLedgerTerminated): PoolLedgerTerminated
load-agent-1  |     at LegacyIndyProofFormatService.getCredentialDefinitions (/load-agent/load-agent/node_modules/@aries-framework/anoncreds/src/formats/LegacyIndyProofFormatService.ts:517:15)
load-agent-1  |     at async LegacyIndyProofFormatService.createProof (/load-agent/load-agent/node_modules/@aries-framework/anoncreds/src/formats/LegacyIndyProofFormatService.ts:602:35)
load-agent-1  |     at async LegacyIndyProofFormatService.acceptRequest (/load-agent/load-agent/node_modules/@aries-framework/anoncreds/src/formats/LegacyIndyProofFormatService.ts:187:19)
load-agent-1  |     at async V1ProofProtocol.acceptRequest (/load-agent/load-agent/node_modules/@aries-framework/anoncreds/src/protocols/proofs/v1/V1ProofProtocol.ts:592:28)
load-agent-1  |     at async ProofsApi.acceptRequest (/load-agent/load-agent/node_modules/@aries-framework/core/src/modules/proofs/ProofsApi.ts:301:25)
load-agent-1  |     at async EventEmitter.onRequest (/load-agent/load-agent/agent.ts:405:9) {
load-agent-1  |   [cause]: undefined
load-agent-1  | }
load-agent-1  | AriesFrameworkError: Credential definition not found for id DGxFt25rfxSecGiHDt79J3:3:CL:249336:rev2: unable to resolve credential definition: IndyError(PoolLedgerTerminated): PoolLedgerTerminated
load-agent-1  |     at LegacyIndyProofFormatService.getCredentialDefinitions (/load-agent/load-agent/node_modules/@aries-framework/anoncreds/src/formats/LegacyIndyProofFormatService.ts:517:15)
load-agent-1  |     at async LegacyIndyProofFormatService.createProof (/load-agent/load-agent/node_modules/@aries-framework/anoncreds/src/formats/LegacyIndyProofFormatService.ts:602:35)
load-agent-1  |     at async LegacyIndyProofFormatService.acceptRequest (/load-agent/load-agent/node_modules/@aries-framework/anoncreds/src/formats/LegacyIndyProofFormatService.ts:187:19)
load-agent-1  |     at async V1ProofProtocol.acceptRequest (/load-agent/load-agent/node_modules/@aries-framework/anoncreds/src/protocols/proofs/v1/V1ProofProtocol.ts:592:28)
load-agent-1  |     at async ProofsApi.acceptRequest (/load-agent/load-agent/node_modules/@aries-framework/core/src/modules/proofs/ProofsApi.ts:301:25)
load-agent-1  |     at async EventEmitter.onRequest (/load-agent/load-agent/agent.ts:405:9) {
load-agent-1  |   [cause]: undefined
load-agent-1  | }

```

**Comment by swcurran** [comment]
Shouldn’t this and related PRs be merged?  Any reason for not merging them?

**Comment by loneil** [comment]
> Shouldn’t this and related PRs be merged? Any reason for not merging them?

Think these PRs and where they should go was TBD in this issue?
https://github.com/bcgov/aries-load-generator/issues/10

I might have some new tweaks shortly though with recent Akrida changes (at the least changing some repo links to OWF).

The PRs here are just documentation/steps so no code releases involved or anything. If this is the right repo then no issue merging them in.

**Comment by swcurran** [comment]
Let’s rename the repository to something like “akrida-bc-load-generator-scripts” and merge them ASAP.  We don’t want to loss site of these.

**Comment by swcurran** [comment]
@loneil — is this ready to go, or are you going to update it with the latest Akrida update before we merge it?

**Comment by loneil** [comment]
Reorged docs https://github.com/bcgov/akrida-bc-load-generator-scripts/pull/11

**Pull request closed without merging**
